### PR TITLE
Fix JSX renderer to correctly render enumerated properties

### LINKED ISSUE #429: `jsx` renderer with `jsx: false` does not render `draggable` correctly
```tsx
import { h } from 'preact';
import { render } from 'preact-render-to-string/jsx';

const node = h('div', { draggable: true });
console.log(render(node, {}, { pretty: true, jsx: false }));
```

Output:
```html
<div draggable></div>
```

According to the Preact types (https://github.com/preactjs/preact/blob/5e183563a101de2d7a750e7c606d0b13677637f1/src/dom.d.ts#L1267):

```
	draggable?: Signalish<boolean | undefined>;
```

From https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes/draggabler:

> Warning: This attribute is [enumerated](https://developer.mozilla.org/en-US/docs/Glossary/Enumerated) and not Boolean. A value of true or false is mandatory, and shorthand like `` is forbidden. The correct usage is ``.

Either this renderer needs to be fixed, or the upstream types need to be fixed (https://github.com/preactjs/preact/issues/4926).

### PR DESCRIPTION
**Pull request by reteps**
Closes #429

### CODE REVIEW

**Review by reteps — COMMENTED** [review]
self-review

File: src/pretty.js [hunk 1]
```diff
@@ -22,7 +23,7 @@ import { options, Fragment } from 'preact';
 const UNNAMED = [];
 
 const EMPTY_ARR = [];
-
+const EMPTY_STR = '';
```
Comment (rschristian) [inline src/pretty.js:26]: Nit:

```suggestion
const EMPTY_STR = '';

```

**Review by rschristian — APPROVED** [review]
Thanks!
